version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
     pre_install:
       - pip install mkdocs-material

# Build documentation with Mkdocs
mkdocs:
   configuration: mkdocs.yml

# Dependencies required to build your docs
#python:
#   install:
#   - requirements: requirements.txt
#
